services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    ports:
    - 9200:9200
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    networks:
    - es-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.15
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    networks:
    - es-network

networks:
  es-network:
   driver: bridge

volumes:
    elasticsearch-data:
        driver: local
        